### ISSUE TITLE
Site does not load, probably due to tracking control (uBlock Origin, Privacy Possum, Decentraleyes, or Firefox tracking protection, or a combination)

### ISSUE THREAD

**Issue by mlncn** [open-company/open-company-web#1171]
The carrot logo/watermark appears briefly, and then the screen is white:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js. (Reason: CORS request did not succeed).

leading of course to a $/JQuery not defined error.

**Comment by mlncn** [comment]
OK can confirm that disabling [Decentraleyes](https://decentraleyes.org/) makes the site work, or at least the https://carrot.io/sign-up/profile page.

So seems likely that it's the fault of that plugin (like did it switch a local JQuery library to Google's??  That is rather the opposite of the reason for using it!), but perhaps it's something Open Company can work around or do something better so it's not confused with an external tracker.

And thanks for being LibreSaaS!

**Comment by bago2k4** [comment]
Thanks @mlncn for reporting this issue. I installed Decentraleyes on Chrome 88.0.4324.96 on macOS Mojave 10.14.6 but I wasn't able to replicate your issue.

I started from the homepage, then Start free and signed up.
I also used an incognito window with only that plugin enabled and the console closed (to avoid any cache manipulation) but no lock.

I think you are right about the plugin being the culprit, I have had similar issues with ad-blockers in the past. Probably there is more causing the issue, like another plugin (like an ad-blocker or similar) that used together leads to this problem.

Do you have any other similar plugin running? Or any custom configuration of the Decentraleyes?

Cheers
