### ISSUE TITLE
Dashboard UX: Navigating using browser back button 

### ISSUE THREAD

**Issue by garbnzgh** [open-company/open-company-web#125]
Expected behavior: 
1) If I'm on a company dashboard: https://opencompany.com/buffer and I
2) Click into a topic card, e.g. "We reached the 50.." 
3) From the topic card I use the browser back button and 
4) I return to the company dashboard

Observed behavior:
1) If I'm on a company dashboard: https://opencompany.com/buffer and I
2) Click into a topic card, e.g. "We reached the 50.." 
3) From the topic card I use the browser back button 
4) The company /profile is displayed and *then* 
5) I return to the company dashboard

This is confusing because I didn't visit the profile in between, makes it feel like the back button is broken in the browser... 

![screen shot 2016-05-30 at 4 41 51 pm](https://cloud.githubusercontent.com/assets/763664/15658065/e7481464-2685-11e6-81bd-9ba22930422f.png)
![screen shot 2016-05-30 at 4 41 55 pm](https://cloud.githubusercontent.com/assets/763664/15658071/ee4158d4-2685-11e6-87ab-7c4c0770edc2.png)
![screen shot 2016-05-30 at 4 41 59 pm](https://cloud.githubusercontent.com/assets/763664/15658072/f2b072c4-2685-11e6-8058-08cc0bbb4641.png)

**Comment by belucid** [comment]
Scheduled for this card: https://trello.com/c/PJxhfRFK

**Comment by garbnzgh** [comment]
Seemingly related issue: If I'm on a company's dashboard and click the company's name, it looks like the browser hits /profile before displaying the dashboard again.

**Comment by belucid** [comment]
https://github.com/open-company/open-company-web/pull/156

**Comment by belucid** [comment]
Done.
