### ISSUE TITLE
Design Enhancement: Core Topic Card Placeholders

### ISSUE THREAD

**Issue by garbnzgh** [open-company/open-company-web#126]
Design a state for core topic placeholders to visual distinguish them from topic cards the user has started

![screen shot 2016-05-30 at 5 19 10 pm](https://cloud.githubusercontent.com/assets/763664/15658559/d9cfb408-268b-11e6-9441-02db25335e55.png)

**Comment by garbnzgh** [comment]
@belucid Should I hold on designing this pending the work @stulev is doing today on new user experience? Seems like the direction you decide to go in will determine whether this item is still needed?

**Comment by belucid** [comment]
No, because every time you add a suggested topic for the first time @garbnzgh it is a placeholder until you put some of your own content into it.

**Comment by garbnzgh** [comment]
Makes sense, will prioritize

**Comment by garbnzgh** [comment]
This design addresses placeholder text on card detail (design and ux), a refinement to when the post button is displayed, and a suggestion for simplifying the flow, removing several unnecessary steps. If you read my notes in the design file it may influence your thinking on the new user experience and whether or not placeholder cards are necessary on the dashboard.

![placeholder text creating topic](https://cloud.githubusercontent.com/assets/763664/15730548/a12ad9a0-283b-11e6-9aee-9a9f03dd881d.png)

**Comment by garbnzgh** [comment]
This approach also applies to simplifying (by several steps) the creating new topic user flow @belucid

**Comment by stulev** [comment]
Love this approach.

**Comment by belucid** [comment]
Done.
