### ISSUE TITLE
Share Snapshot: Bottom Padding

### ISSUE THREAD

**Issue by garbnzgh** [open-company/open-company-web#127]
When user initiates the "share a snapshot" flow, if they don't have many snapshots the placement/treatment of the footer draws too much attention and is distracting from the share ux. 

A quick and easy fix is to **add 400px to the bottom padding of div.topics-columns div.topics-column-container in the "share a snapshot" view** so the footer is pushed down. **Alternatively I'd suggest not displaying the footer here.**

Screenshot of the issue:
![screen shot 2016-05-30 at 7 31 21 pm](https://cloud.githubusercontent.com/assets/763664/15659705/6b5af6f6-269d-11e6-9267-494174d74c2c.png)

**Comment by belucid** [comment]
@bago2k4 Let's just remove the footer from this share screen.

**Comment by belucid** [comment]
Done.
