### ISSUE TITLE
Design Enhancement: Need Confirmation Screen in "Share Snapshot" UX

### ISSUE THREAD

**Issue by garbnzgh** [open-company/open-company-web#128]
Strongly recommend having a confirmation screen displayed after the user has shared to slack or email. Right now the only indication that something happened is the button language changes to "sent." 

This makes it feel like the snapshot didn't go through. As a user, I'd expect to see a confirmation message e.g. "Your snapshot was sent via [Slack / email]." Return to dashboard (with link to your dashboard).

Screenshot of current confirmation screen:
<img width="954" alt="screen shot 2016-05-30 at 7 36 29 pm" src="https://cloud.githubusercontent.com/assets/763664/15659733/26226492-269e-11e6-9011-8c13c364579a.png">

**Comment by belucid** [comment]
+1

We went with changing the button only because there was no design.

I notice in the screenshot this is another case of you seeing a "?" rather than the real icon. Did you look into that?

**Comment by garbnzgh** [comment]
> We went with changing the button only because there was no design.

Will send one. I didn't know that design was a blocker on building this. 

> I notice in the screenshot this is another case of you seeing a "?" rather than the real icon. Did you look into that?

I didn't look into it yet since it seems to be isolated to my computer. Seems less important than other larger product / ux stuff right now..? If you'd like me to prioritize investigating this please let me know.

**Comment by garbnzgh** [comment]
Design for share to slack confirmation modal: 
![share confirm](https://cloud.githubusercontent.com/assets/763664/15670174/03082286-26f2-11e6-8dc8-b4e1b7a9fcd5.png)

**Comment by garbnzgh** [comment]
@belucid need anything else on this?

**Comment by belucid** [comment]
I think we are good on this, thanks @garbnzgh

**Comment by belucid** [comment]
@garbnzgh can we get the sketch on this in Dropbox?

**Comment by garbnzgh** [comment]
@belucid yes, same sketch file as the other modal  https://www.dropbox.com/s/th9ueyd6e8gu4ho/opencompany%20-%20share%20confirm%20modals%2001.sketch?dl=0

**Comment by belucid** [comment]
Done.
