### ISSUE TITLE
Share UX: Shared a snapshot to Slack but nothing went through to my team

### ISSUE THREAD

**Issue by garbnzgh** [open-company/open-company-web#129]
(Possibly not developed yet.. if so ignore)

When I shared a snapshot to Slack, I saw the "Sent" confirmation in the button on the share screen but no snapshot was shared to my team's slack account. 

<img width="954" alt="screen shot 2016-05-30 at 7 36 29 pm" src="https://cloud.githubusercontent.com/assets/763664/15659744/8258cd0a-269e-11e6-90ea-836d511b277f.png">

<img width="879" alt="screen shot 2016-05-30 at 7 41 43 pm" src="https://cloud.githubusercontent.com/assets/763664/15659750/90d182e6-269e-11e6-9e5e-3169171978d2.png">

**Comment by belucid** [comment]
Not fully implemented yet.
