### ISSUE TITLE
Design Enhancement: Share URL button treatment

### ISSUE THREAD

**Issue by garbnzgh** [open-company/open-company-web#130]
The share url button has an email icon in it implying email functionality, but it only gives you a link to copy and share manually. Swap in link icon instead of email icon on this button for ux clarity.

<img width="238" alt="screen shot 2016-05-30 at 7 43 37 pm" src="https://cloud.githubusercontent.com/assets/763664/15659772/d23337fc-269e-11e6-9ac4-e61871dd7c08.png">

**Comment by belucid** [comment]
@bago2k4 switch to a link (chain link thingie) icon.

**Comment by belucid** [comment]
Done.
