### ISSUE TITLE
Share URL link broken

### ISSUE THREAD

**Issue by garbnzgh** [open-company/open-company-web#131]
The link generated in the share snapshot > share url modal is not working:

e.g. https://opencompany.comi.opencompany.com/companies/under-after/updates/april-2016-update-39b8

<img width="633" alt="screen shot 2016-05-30 at 7 44 49 pm" src="https://cloud.githubusercontent.com/assets/763664/15659796/17fd3968-269f-11e6-8164-11b20b7ce171.png">

**Comment by belucid** [comment]
Fixed in https://github.com/open-company/open-company-web/pull/124
