### ISSUE TITLE
"Learn More" link in footer links to Opencompany.io

### ISSUE THREAD

**Issue by garbnzgh** [open-company/open-company-web#132]
"Learn More" link in footer links to opencompany.io. Expected behavior = links to opencompany.com

<img width="437" alt="screen shot 2016-05-30 at 7 46 11 pm" src="https://cloud.githubusercontent.com/assets/763664/15659807/4101f696-269f-11e6-9a30-9cc613d147a0.png">

**Comment by belucid** [comment]
This is as intended right now until the new website design is implemented at opencompany.com.

**Comment by garbnzgh** [comment]
Ok, then should the link in the footer also go to opencompany.io? I may be missing something here but it seems unexpected from a ux-perspective if someone is on opencompany.com to take them to a different domain when there is a homepage on opencompany.com too?
