### ISSUE TITLE
Design Enhancement: Character count style while editing topic #lowpriority

### ISSUE THREAD

**Issue by garbnzgh** [open-company/open-company-web#133]
Need design treatment for character count style on topic detail edit

<img width="755" alt="screen shot 2016-05-30 at 7 50 29 pm" src="https://cloud.githubusercontent.com/assets/763664/15659834/dcf11262-269f-11e6-85ef-e0af9943acd1.png">

**Comment by garbnzgh** [comment]
Updating to lowpriority per feedback from Stuart

**Comment by belucid** [comment]
Moved to: https://trello.com/c/AAxCFFoQ
