### ISSUE TITLE
Editing Topic > Editing Link Behavior

### ISSUE THREAD

**Issue by garbnzgh** [open-company/open-company-web#134]
While editing topic update, there's some strange ux with editing links.

Current Behavior 
1) Select text, editing tools modal appears
2) Click to add link
3) Enter link url
4) Click elsewhere on the screen to close editing tools
5) Select some of the text within the hyperlinked text I just added
6) Click the link button again
7) Hyperlink removed, but only for the text I selected within the hyperlinked text

Expected behavior
... 7) Hyperlink removed entirely, for that whole hyperlinked text (see medium.com)

<img width="680" alt="screen shot 2016-05-30 at 7 54 02 pm" src="https://cloud.githubusercontent.com/assets/763664/15659894/f5abb8ec-26a0-11e6-8628-d8cf4052e5f6.png">
<img width="633" alt="screen shot 2016-05-30 at 7 54 07 pm" src="https://cloud.githubusercontent.com/assets/763664/15659896/f93c62fe-26a0-11e6-87e1-5b88866792f0.png">
<img width="691" alt="screen shot 2016-05-30 at 7 54 10 pm" src="https://cloud.githubusercontent.com/assets/763664/15659898/fbda476a-26a0-11e6-92ae-505558c58b72.png">
<img width="650" alt="screen shot 2016-05-30 at 7 54 15 pm" src="https://cloud.githubusercontent.com/assets/763664/15659900/fed07390-26a0-11e6-8895-cdee2d5a25c8.png">
<img width="735" alt="screen shot 2016-05-30 at 7 54 21 pm" src="https://cloud.githubusercontent.com/assets/763664/15659901/016fd686-26a1-11e6-9f4e-bbcfb590cbfb.png">
<img width="632" alt="screen shot 2016-05-30 at 7 54 24 pm" src="https://cloud.githubusercontent.com/assets/763664/15659902/04351e3a-26a1-11e6-9711-26b273441ba6.png">

**Comment by belucid** [comment]
@martinklepsch not urgent.
