### ISSUE TITLE
[UX] Difference in text editing tools

### ISSUE THREAD

**Issue by garbnzgh** [open-company/open-company-web#135]
There's some difference in the options you're providing to users versus what was in the designs. 

In designs: 
<img width="430" alt="screen shot 2016-05-30 at 8 02 37 pm" src="https://cloud.githubusercontent.com/assets/763664/15659934/9724d8a2-26a1-11e6-84e7-12c88d88a7b3.png">

In current build:
<img width="480" alt="screen shot 2016-05-30 at 8 04 02 pm" src="https://cloud.githubusercontent.com/assets/763664/15659938/ad00c96a-26a1-11e6-8380-61a9b0c3f5a9.png">

I'd suggest, from a design perspective, bold, h1, and h2 are the way to enable emphasis. I'd strongly suggest removing italic and strikethrough options. Strikethrough is visually crazy and will disrupt the reading experience. 

Why not enable adding h1's? 

Are inline imgs out of scope for now? Images are one of the few "hacks" that give people the ability to really customize and tell their stories visually.

**Comment by belucid** [comment]
The idea of no H1's is to respect the semantic web somewhat. The H1 is the headline we provide as a separate field. "Internal" headlines are therefore H2. We could provide an H2 and H3 if you think multiple levels of headlines is important for some reason, but it just seems fiddly to me.

Inline images are done w/ the (+) button on the left, not with the toolbar. Having to select text to add an image was wonky. But the fact that you didn't discover the image adding is alarming.

We're pretty happy with italics and strikethrough. Strikethrough was requested specifically by @stulev. I think the idea of strikethrough is not to use it extensively, but to make a small ~~rhetorical~~ important point by striking through a word or two.

I think we're pretty happy with the toolbar @garbnzgh

**Comment by garbnzgh** [comment]
Ok. My understanding is that multiple h1s are allowed per page content sections in html5: http://webdesign.tutsplus.com/articles/the-truth-about-multiple-h1-tags-in-the-html5-era--webdesign-16824 – Medium.com enables users to add both h1s and h2s. 

> "if you think multiple levels of headlines is important for some reason.."

 Yes if they want to have structure / sections within a topic update. 

> "Inline images are done w/ the (+) button on the left, not with the toolbar. Having to select text to add an image was wonky." 
I did miss this.

**Comment by garbnzgh** [comment]
Also I didn't realize the toolbar was available after selecting texting. I thought you could click while in edit mode to get toolbar options, (why I had inserting images in the toolbar, and inserting charts in the toolbar in earlier designs).

**Comment by belucid** [comment]
Sure multiple H1's are allowed. But that is then indicating those H1 headers are at the same level. Semantically any header you add in the content of the topic is secondary to the header of the whole topic.

I do see the case for an H2 and an H3 if you think multiple levels of headings in the content are important. We'd just need the body content styling for H3 from you to add that.

**Comment by belucid** [comment]
The idea @garbnzgh is adding a chart would also be under the (+) button (as well as other inline elements, like embedded video).

If you have any design suggestions of how the (+) would be less likely to be missed, we're all ears.

**Comment by garbnzgh** [comment]
Ok – I'm going to close this issue out and split out the two design tasks: (+) more prominent and H3 text style.
