### ISSUE TITLE
[Design QA] Request for Busy State Indicator #lowpriority

### ISSUE THREAD

**Issue by garbnzgh** [open-company/open-company-web#136]
> Another is a busy state that works outside the yellow button. We used the “yellow button” busy in another place where we need a busy state and it looks pretty bad.

@belucid can you point me to where else you are using the busy state indicator (loading gif) outside of yellow buttons?

**Comment by belucid** [comment]
We originally had this in the share dialog before we reworked the flow. The busy states are now all in yellow buttons.

I'd say this is just a low-priority need for the UI library at this point. No longer urgent.

**Comment by garbnzgh** [comment]
Gotcha, ok. Thanks!

**Comment by belucid** [comment]
Maybe this will be in the style guide only @garbnzgh ? We'd probably use it on buttons like the archive button if we had it.
