### ISSUE TITLE
[Design QA] Request for secondary link design treatment

### ISSUE THREAD

**Issue by garbnzgh** [open-company/open-company-web#137]
> non-user content links: so… secondary links in a UI context 

![opencompany - startup transparency made simple 2016-05-26 11-16-34](https://cloud.githubusercontent.com/assets/763664/15671310/403651fe-26f8-11e6-94d9-0eb7dc8ba0d6.png)

**Comment by garbnzgh** [comment]
@belucid design attached for secondary link treatment as well as updated design for this modal. 

![share url](https://cloud.githubusercontent.com/assets/763664/15716073/e7e95832-27ee-11e6-8613-c169f9984d94.png)

**Comment by belucid** [comment]
@garbnzgh can we get the sketch for this update in Dropbox?

**Comment by garbnzgh** [comment]
Yes https://www.dropbox.com/s/th9ueyd6e8gu4ho/opencompany%20-%20share%20confirm%20modals%2001.sketch?dl=0

**Comment by belucid** [comment]
Done.
