### ISSUE TITLE
[Design QA] "Mobile Nav Bar Size" #lowpriority

### ISSUE THREAD

**Issue by garbnzgh** [open-company/open-company-web#138]
Requested on design priorities doc: 
> mobile nav bar size 

@belucid can you provide a little more detail just so I'm clear on what you'd like me to check for this qa task?

**Comment by belucid** [comment]
I don't remember this one @garbnzgh 

Not sure what that means.

**Comment by garbnzgh** [comment]
From Stuart

> What I meant is that on mobile, the area we use for logo, company name and menu button takes up 20% of the real estate. I wondered if it shouldn't be thinner, or perhaps get smaller when scrolling. It's not a first world problem, but something to keep on the list. Maybe it's just as simple as making it a bit thinner to see how it feels at first, or you may say it's fine as is.

**Comment by belucid** [comment]
Moved to: https://trello.com/c/soVw2xCQ
