### ISSUE TITLE
[UX] Make (+) visible to users when editing before they enter a new paragraph 

### ISSUE THREAD

**Issue by garbnzgh** [open-company/open-company-web#142]
> If you have any design suggestions of how the (+) would be less likely to be missed, we're all ears.

**Comment by garbnzgh** [comment]
Ok I figured out why I didn't see it. The (+) is not displayed when editing the placeholder content, only when you enter a new paragraph.

 I'd suggest displaying the (+) where the new paragraph would be as soon as the user enters edit mode instead of only displaying it when they add a new paragraph. That way the user will know they can add images. Currently if I switch into edit mode and edit the placeholder content without adding a new paragraph the (+) is never displayed. 

The design treatment is fine from my perspective, if it is displayed.

![screen shot 2016-06-01 at 10 35 06 am](https://cloud.githubusercontent.com/assets/763664/15713550/dfbe13a0-27e4-11e6-9e7c-0aa40af944f3.png)

![screen shot 2016-06-01 at 10 35 11 am](https://cloud.githubusercontent.com/assets/763664/15713563/e322250e-27e4-11e6-96fa-ea8d30698587.png)
 
![screen shot 2016-06-01 at 10 35 20 am](https://cloud.githubusercontent.com/assets/763664/15713568/ea2d28bc-27e4-11e6-981b-3e83d9441107.png)

**Comment by belucid** [comment]
That's actually pointing out a different problem @garbnzgh , the placeholder content is intended to be more like prompt text, disappearing once you type something, only there when the topic is blank. That'd fix this issue.

**Comment by garbnzgh** [comment]
Ok, so then in the case where placeholder content disappears, the (+) would still be visible as soon as you enter edit mode, before you press enter for a new paragraph? If so then I think this change would solve the visibility issue.

**Comment by belucid** [comment]
That's the idea. I agree, that should close this @garbnzgh .
