### ISSUE TITLE
[Design QA] On share a snapshot screen, extra white space below footer looks awkward #lowpriority

### ISSUE THREAD

**Issue by garbnzgh** [open-company/open-company-web#149]
![screen shot 2016-06-06 at 3 38 59 pm](https://cloud.githubusercontent.com/assets/763664/15835223/f612a5a0-2bfc-11e6-8b9a-3c3613d9c922.png)

Suggestions: 
1. Remove gold horizontal bar from below footer. 
2. Have footer background color extend to bottom of page OR have footer positioned to bottom of page height.

**Comment by belucid** [comment]
Fixed.
