### ISSUE TITLE
Problem running locally

### ISSUE THREAD

**Issue by podviaznikov** [open-company/open-company-web#48]
Hi,

I'm run `lein devcards!` locally but couldn't see any results. Are the instructions accurate?

<img width="1279" alt="localhost_3449_devcards_and_skitch" src="https://cloud.githubusercontent.com/assets/429706/11464779/c3663bf8-96e7-11e5-9d6c-85d05f9cd45e.png">

**Comment by belucid** [comment]
@bago2k4 I confirmed that devcards are broken locally on mainline right now. Can you take a look when you get a chance.

**Comment by bago2k4** [comment]
@podviaznikov a PR for a fix is out, thanks for the catch

**Comment by belucid** [comment]
@podviaznikov the devcards fix is merge into mainline.
